name: jesseconnr
favicon: null
layout_spectrum: 1
typography_spectrum: 0.9988167132250965
title: Jesse Connor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73889121-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 1
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 1
purpose: []
